apiVersion: v1
kind: ConfigMap
metadata:
  name: image-trace-config
  namespace: image-trace
data:
  REDIS_URL: redis://image-trace-redis:6379/1
  MINIO_ENDPOINT: image-trace-minio:9000
  MINIO_SECURE: "false"
  PYTHONPATH: /app
